export enum TypeFinancialMovement {
  INCOMMING_WIRE_DOMESTIC = "INCOMMING_WIRE_DOMESTIC",
  OUTGOING_WIRE_DOMESTIC = "OUTGOING_WIRE_DOMESTIC",
  INCOMMING_WIRE_INTERNATIONAL = "INCOMMING_WIRE_INTERNATIONAL",
  OUTGOING_WIRE_INTERNATIONAL = "OUTGOING_WIRE_INTERNATIONAL",
  SWAP = "SWAP",

  INCOMMING_ACH_USA = "INCOMMING_ACH_USA",
  OUTGOING_ACH_USA = "OUTGOING_ACH_USA",

  OUTGOING_PAYMENT_BUSINESS_ALLIE = "OUTGOING_PAYMENT_BUSINESS_ALLIE",

  INCOMMING_ACH_PA = "INCOMMING_ACH_PA",
  OUTGOING_ACH_PA = "OUTGOING_ACH_PA",

  CARD_RECHARGE = "CARD_RECHARGE",
  ISSUE_CARD = "ISSUE_CARD",
}
