export enum TypeFinancialMovement {
  INCOMMING_WIRE_DOMESTIC = "INCOMMING_WIRE_DOMESTIC",
  OUTGOING_WIRE_DOMESTIC = "OUTGOING_WIRE_DOMESTIC",
  INCOMMING_WIRE_INTERNATIONAL = "INCOMMING_WIRE_INTERNATIONAL",
  OUTGOING_WIRE_INTERNATIONAL = "OUTGOING_WIRE_INTERNATIONAL",
  SWAP = "SWAP",

  INCOMMING_ACH_USD = "INCOMMING_ACH_USD",
  OUTGOING_ACH_USD = "OUTGOING_ACH_USD",

  OUTGOING_PAYMENT_BUSINESS_ALLIE = "OUTGOING_PAYMENT_BUSINESS_ALLIE",

  INCOMMING_ACH_PAB_EXTERNAL = "INCOMMING_ACH_PAB_EXTERNAL",
  OUTGOING_ACH_PAB_EXTERNAL = "OUTGOING_ACH_PAB_EXTERNAL",

  CARD_RECHARGE = "CARD_RECHARGE",
  ISSUE_CARD = "ISSUE_CARD",
}
