export enum AccountStatus {
  REGISTERED = "REGISTERED",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  SUBMITTED = "SUBMITTED",
  PROCESSING = "PROCESSING",
  FROZEN = "FROZEN",
  SUSPECTED_FRAUD = "SUSPECTED_FRAUD",
}
