export enum AccountStatus {
  REGISTERED = "REGISTERED",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  SUBMITTED = "SUBMITTED",
  PROCESSING = "PROCESSING",
}
