export enum Layer2ApplicationWebhookStatusEnum {
  APPLICATION_READY_FOR_SUBMISSION = "APPLICATION_READY_FOR_SUBMISSION",
  APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED",
  APPLICATION_PROCESSING = "APPLICATION_PROCESSING",
  APPLICATION_CHANGE_REQUESTED = "APPLICATION_CHANGE_REQUESTED",
  APPLICATION_REJECTED = "APPLICATION_REJECTED",
  APPLICATION_APPROVED = "APPLICATION_APPROVED",
}
