export enum Layer2ApplicationStatusEnum {
  INCOMPLETE = "INCOMPLETE",
  READY_FOR_SUBMISSION = "READY_FOR_SUBMISSION",
  SUBMITTED = "SUBMITTED",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}
