export enum BusinessOpportunityStatus {
  REGISTERED_OPPORTUNITY = "REGISTERED_OPPORTUNITY",
  OPPORTUNITY_WITH_REGISTERED_ACCOUNT = "OPPORTUNITY_WITH_REGISTERED_ACCOUNT",
  OPPORTUNITY_WITH_ACTIVE_ACCOUNT = "OPPORTUNITY_WITH_ACTIVE_ACCOUNT",
}
