export enum ReferredStatus {
  REFERRED_REGISTERED_BY_ALLIE = "REFERRED_REGISTERED_BY_ALLIE",
  REFERRED_WITH_REGISTERED_ACCOUNT = "REFERRED_WITH_REGISTERED_ACCOUNT",
  REFERRED_WITH_ACTIVE_ACCOUNT = "REFERRED_WITH_ACTIVE_ACCOUNT",
}
