export enum Layer2Documents {
  PASSPORT = "PASSPORT",
  DRIVERS_LICENCE_FRONT = "DRIVERS_LICENCE_FRONT",
  DRIVERS_LICENCE_BACK = "DRIVERS_LICENCE_BACK",
  LAYER2_ACCOUNT_AGREEMENT = "LAYER2_ACCOUNT_AGREEMENT",
  ACCOUNT_AGREEMENT = "ACCOUNT_AGREEMENT",
}
