export enum WithdrawalStatus {
  PENDING = "PENDING",
  IN_PROCESS = "IN_PROCESS",
  PROCESSED = "PROCESSED",
  CANCELLED = "CANCELLED",
  REVERSED = "REVERSED",
  PROCESS_WITH_ERROR = "PROCESS_WITH_ERROR",
}
